extends Node

var BASIC_DAMAGE = GlobalDefault.BASE_BASIC_DAMAGE
var POWER_1_DAMAGE = GlobalDefault.BASE_POWER_1_DAMAGE
var POWER_2_DAMAGE = GlobalDefault.BASE_POWER_2_DAMAGE
var POWER_3_DAMAGE = GlobalDefault.BASE_POWER_3_DAMAGE

var DAMAGE_BONUS = GlobalDefault.BASE_DAMAGE_BONUS
var FREEZE_TIME = GlobalDefault.BASE_FREEZE_TIME
var HEALING_BONUS = GlobalDefault.BASE_HEALING_BONUS

var POWER1_SPEED = GlobalDefault.BASE_POWER1_SPEED
var POWER2_RADIOUS = GlobalDefault.BASE_POWER2_RADIOUS
var POWER2_SCALE = GlobalDefault.BASE_POWER2_SCALE
var POWER3_ROUNDS = GlobalDefault.BASE_POWER3_ROUNDS

func reset_globals():
	BASIC_DAMAGE = GlobalDefault.BASE_BASIC_DAMAGE
	POWER_1_DAMAGE = GlobalDefault.BASE_POWER_1_DAMAGE
	POWER_2_DAMAGE = GlobalDefault.BASE_POWER_2_DAMAGE
	POWER_3_DAMAGE = GlobalDefault.BASE_POWER_3_DAMAGE
	
	DAMAGE_BONUS = GlobalDefault.BASE_DAMAGE_BONUS
	FREEZE_TIME = GlobalDefault.BASE_FREEZE_TIME
	HEALING_BONUS = GlobalDefault.BASE_HEALING_BONUS
	
	POWER1_SPEED = GlobalDefault.BASE_POWER1_SPEED
	POWER2_RADIOUS = GlobalDefault.BASE_POWER2_RADIOUS
	POWER2_SCALE = GlobalDefault.BASE_POWER2_SCALE
	POWER3_ROUNDS = GlobalDefault.BASE_POWER3_ROUNDS
