extends Node

var BASIC_DAMAGE = GlobalDefault.BASE_BASIC_DAMAGE
var POWER_1_DAMAGE = GlobalDefault.BASE_POWER_1_DAMAGE
var POWER_2_DAMAGE = GlobalDefault.BASE_POWER_2_DAMAGE
var POWER_3_DAMAGE = GlobalDefault.BASE_POWER_3_DAMAGE

var DAMAGE_BONUS = GlobalDefault.BASE_DAMAGE_BONUS
var FREEZE_TIME = GlobalDefault.BASE_FREEZE_TIME
var HEALING_BONUS = GlobalDefault.BASE_HEALING_BONUS
