extends Node

var BASE_BASIC_DAMAGE = 100
var BASE_POWER_1_DAMAGE = 10
var BASE_POWER_2_DAMAGE = 137
var BASE_POWER_3_DAMAGE = 182

var BASE_DAMAGE_BONUS = 0.1
var BASE_FREEZE_TIME = 4.0
var BASE_HEALING_BONUS = 0.1
